packages:
  - apps/*
  - packages/*
  - scripts

catalogMode: prefer

catalog:
  "@effect/ai-openrouter": 4.0.0-beta.99
  "@effect/platform-node": 4.0.0-beta.99
  "@effect/sql-sqlite-node": 4.0.0-beta.99
  "@effect/vitest": 4.0.0-beta.99
  "@types/node": ^24
  effect: 4.0.0-beta.99
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
overrides:
  postcss: 8.5.19
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  msgpackr-extract: true
